############################################################
#
# mysql
#
############################################################
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/step
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: app-order

server:
  port: 8081

mycloud:
  prd:
    url: http://127.0.0.1:8080/detail/

#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
           defaultZone: http://kabu:kabu@127.0.0.1:8100/eureka/,http://kabu:kabu@127.0.0.1:9100/eureka/
#因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
#是否需要从eureka上检索服务
    fetch-registry: true